services:
  solver:
    build: .
    container_name: chamber-of-echos.solver
    command:
      # TODO:
      #   宛先のアドレスに書き換えてください (未指定では `127.0.0.1` になります)
      #   ※ 名前解決には対応していません
      # - "203.0.113.1"
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TZ: "Asia/Tokyo"
